"""Added created_at and updated_at columns

Revision ID: fe22aa4131b1
Revises: 864b4506a65f
Create Date: 2025-02-06 00:20:29.925159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe22aa4131b1'
down_revision = '864b4506a65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_item', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
