"""Your migration message here

Revision ID: 864b4506a65f
Revises: 498657287445
Create Date: 2025-02-03 17:52:24.571959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864b4506a65f'
down_revision = '498657287445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auction_item', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
